Repository hpi-swt2/bookkeeper-portal-blue, pull requests merged in 2022-12, with the labels that each got.

#111 Fix Navbar overlap issues
  app/assets/stylesheets/navbar.scss
  app/views/layouts/application.html.erb
Labels: Bug

#110 Add results to search (#16)
  app/controllers/search_controller.rb
  app/views/search/index.html.erb
  spec/features/search/search_spec.rb
Labels: BP-AP, Sprint Backlog

#191 Feature/ap 140 empty search string behavoir
  app/controllers/search_controller.rb
  app/views/search/index.html.erb
  spec/features/search/search_spec.rb
Labels: BP-AP
