Repository hpi-swt2/bookkeeper-portal-blue, pull requests merged in 2023-01, with the labels that each got.

#193 Feature/ap 163 extract item card fragment
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/itemcard.scss
  app/views/partials/_itemcard.html.erb
  app/views/search/index.html.erb
Labels: BP-AP, Sprint Backlog

#221 feature: qr-code scanner
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/video.scss
  app/javascript/controllers/qrscanner_controller.js
  app/views/search/index.html.erb
  config/importmap.rb
Labels: BP-AP

#109 Adapt Search Skeleton to Prototype Design
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/itemcard.scss
  app/views/dashboard/_lent_items.html.erb
  app/views/dashboard/_offered_items.html.erb
  app/views/dashboard/_wishlist.html.erb
  app/views/partials/_itemcard.html.erb
  app/views/search/_filter-modal.html.erb
  app/views/search/_qr-scanner.html.erb
  app/views/search/index.html.erb
  config/locales/de.yml
  config/locales/en.yml
Labels: BP-AP, Sprint Backlog

#256 removed flash button #246
  app/javascript/controllers/qrscanner_controller.js
  app/views/search/_qr-scanner.html.erb
Labels: BP-AP

#255 Fix:search behaviour lowercase search string
  app/helpers/search_helper.rb
  spec/helpers/search_helper_spec.rb
Labels: BP-AP

#270 bug: qrscanner active in background #230
  app/javascript/controllers/qrscanner_controller.js
  app/views/search/_qr-scanner.html.erb
  app/views/search/index.html.erb
Labels: Bug, BP-AP

#271 bug: qrscanner ignore non-existing items #247
  app/javascript/controllers/qrscanner_controller.js
Labels: Bug, BP-AP

#294 Feature: Show all items on empty search string
  app/controllers/search_controller.rb
  app/helpers/search_helper.rb
  app/views/search/index.html.erb
  spec/features/search/search_spec.rb
  spec/helpers/search_helper_spec.rb
Labels: BP-AP

#205 Feature: Model for statistics
  app/controllers/items_controller.rb
  app/helpers/audit_event_helper.rb
  app/helpers/statistics_helper.rb
  app/models/audit_event.rb
  app/models/item.rb
  db/migrate/20230103101636_create_audit_events.rb
  db/schema.rb
  spec/factories/audit_events.rb
  spec/features/items/show.html.erb_spec.rb
  spec/features/notifications/return_request_notifications_spec.rb
  spec/features/request/accept_lend_request_spec.rb
  spec/models/audit_event_spec.rb
  spec/requests/items_spec.rb
Labels: BP-AP

#324 available items are now always on top of search results #319
  app/helpers/search_helper.rb
  spec/factories/items.rb
  spec/features/search/search_spec.rb
Labels: BP-AP

#318 Feature/ap 248 item popularity
  app/helpers/statistics_helper.rb
  app/models/item.rb
  spec/factories/audit_events.rb
  spec/factories/items.rb
  spec/helpers/search_helper_spec.rb
Labels: BP-AP

#329 Add margin to button
  app/views/search/index.html.erb
Labels: BP-AP

#328 Fix: sql injection search page
  app/helpers/search_helper.rb
  spec/helpers/search_helper_spec.rb
Labels: BP-AP

#330 Sort-search-results button
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/ordering.scss
  app/controllers/search_controller.rb
  app/views/search/index.html.erb
  config/locales/de.yml
  config/locales/en.yml
  spec/views/search/index.html.erb_spec.rb
Labels: BP-AP

#313 rename QR-Code Herunterladen in de and en
  config/locales/de.yml
  config/locales/en.yml
Labels: BP-BR

#340 Feature/ap 249 item list popularity
  app/helpers/statistics_helper.rb
  spec/helpers/search_helper_spec.rb
Labels: BP-AP

#341 Feature/ap 326 sort search results by name
  app/controllers/search_controller.rb
  app/helpers/search_helper.rb
  app/views/search/index.html.erb
  spec/factories/items.rb
  spec/features/search/search_spec.rb
Labels: BP-AP

#265 Feature: #19 Filter Options
  app/assets/stylesheets/buttons.scss
  app/controllers/search_controller.rb
  app/helpers/search_helper.rb
  app/views/search/_filter-modal.html.erb
  app/views/search/index.html.erb
  config/locales/de.yml
  config/locales/en.yml
  spec/features/search/search_spec.rb
Labels: BP-AP

#359 feature: remove "sort-by" option from sort dropdown menu
  app/controllers/search_controller.rb
  config/locales/de.yml
  config/locales/en.yml
  db/schema.rb
Labels: BP-AP

#346 items can now be sorted by popularity
  app/controllers/search_controller.rb
  spec/features/search/search_spec.rb
Labels: BP-AP

#345 Feature/ap 168 filter option groups
  app/controllers/search_controller.rb
  app/helpers/search_helper.rb
  app/views/search/_filter-modal.html.erb
  app/views/search/index.html.erb
  config/locales/de.yml
  config/locales/en.yml
  spec/features/search/search_spec.rb
Labels: BP-AP

#344 Feature/ap 316 global margin
  app/assets/stylesheets/buttons.scss
  app/views/dashboard/_offered_items.html.erb
  app/views/layouts/application.html.erb
  app/views/notifications/index.html.erb
  app/views/search/index.html.erb
  app/views/users/edit.html.erb
Labels: BP-AP

#369 Feature: show average lend time for item
  app/controllers/items_controller.rb
  app/helpers/statistics_helper.rb
  app/views/items/show.html.erb
  config/locales/de.yml
  config/locales/en.yml
  spec/features/items/show.html.erb_spec.rb
  spec/helpers/search_helper_spec.rb
Labels: BP-AP
